import type { SimulationCase } from "./cli-command-executor-simulation.types";

export const CLI_COMMAND_SIMULATION_MATRIX: SimulationCase[] = [
	{
		name: "run action with all supported optional flags",
		request: {
			action: "run",
			projectId: "default",
			issueKey: "ROY-122",
			allProjects: true,
			poll: true,
			noExitWhenIdle: true,
			concurrency: 2,
			pollIntervalMs: 2500,
			maxPollCycles: 4,
			isolatedWorktrees: true,
		},
		expectedArgs: [
			"run",
			"./packages/cli/src/index.ts",
			"run",
			"--project",
			"default",
			"--issue",
			"ROY-122",
			"--all-projects",
			"--poll",
			"--no-exit-when-idle",
			"--concurrency",
			"2",
			"--poll-interval-ms",
			"2500",
			"--max-poll-cycles",
			"4",
			"--isolated-worktrees",
		],
		commandResult: { code: 0, stdout: "run ok", stderr: "" },
		expectedStatus: "succeeded",
	},
	{
		name: "status action maps non-zero exit to failed result",
		request: {
			action: "status",
			projectId: "default",
			issueKey: "ROY-122",
		},
		expectedArgs: [
			"run",
			"./packages/cli/src/index.ts",
			"status",
			"--project",
			"default",
			"--issue",
			"ROY-122",
		],
		commandResult: { code: 1, stdout: "", stderr: "status failed" },
		expectedStatus: "failed",
		expectedError: "status failed",
	},
	{
		name: "projects action",
		request: { action: "projects" },
		expectedArgs: ["run", "./packages/cli/src/index.ts", "projects"],
		commandResult: { code: 0, stdout: "projects ok", stderr: "" },
		expectedStatus: "succeeded",
	},
	{
		name: "setup action with check flag",
		request: { action: "setup", check: true },
		expectedArgs: ["run", "./packages/cli/src/index.ts", "setup", "--check"],
		commandResult: { code: 0, stdout: "setup ok", stderr: "" },
		expectedStatus: "succeeded",
	},
	{
		name: "skills list action",
		request: { action: "skills", skillsAction: "list", projectId: "api" },
		expectedArgs: [
			"run",
			"./packages/cli/src/index.ts",
			"skills",
			"list",
			"--project",
			"api",
		],
		commandResult: { code: 0, stdout: "skills list ok", stderr: "" },
		expectedStatus: "succeeded",
	},
	{
		name: "skills add action",
		request: {
			action: "skills",
			skillsAction: "add",
			title: "Backend Standard",
			description: "Rules",
			content: "Use consistent module boundaries.",
			projectId: "api",
		},
		expectedArgs: [
			"run",
			"./packages/cli/src/index.ts",
			"skills",
			"add",
			"--title",
			"Backend Standard",
			"--description",
			"Rules",
			"--content",
			"Use consistent module boundaries.",
			"--project",
			"api",
		],
		commandResult: { code: 0, stdout: "skills add ok", stderr: "" },
		expectedStatus: "succeeded",
	},
	{
		name: "skills update action",
		request: {
			action: "skills",
			skillsAction: "update",
			name: "backend-standard",
			description: "Updated description",
		},
		expectedArgs: [
			"run",
			"./packages/cli/src/index.ts",
			"skills",
			"update",
			"backend-standard",
			"--description",
			"Updated description",
		],
		commandResult: { code: 0, stdout: "skills update ok", stderr: "" },
		expectedStatus: "succeeded",
	},
	{
		name: "skills remove action",
		request: {
			action: "skills",
			skillsAction: "remove",
			name: "backend-standard",
			projectId: "default",
		},
		expectedArgs: [
			"run",
			"./packages/cli/src/index.ts",
			"skills",
			"remove",
			"backend-standard",
			"--project",
			"default",
		],
		commandResult: { code: 0, stdout: "skills remove ok", stderr: "" },
		expectedStatus: "succeeded",
	},
	{
		name: "task create action with optional fields",
		request: {
			action: "task",
			taskAction: "create",
			request: "Build a better setup flow",
			projectId: "default",
			nonInteractive: true,
			maxClarificationRounds: 2,
			clarificationAnswers: [{ question: "Who?", answer: "CLI users" }],
		},
		expectedArgs: [
			"run",
			"./packages/cli/src/index.ts",
			"task",
			"create",
			"--request",
			"Build a better setup flow",
			"--project",
			"default",
			"--non-interactive",
			"--max-clarification-rounds",
			"2",
			"--clarifications-json",
			'[{"question":"Who?","answer":"CLI users"}]',
		],
		commandResult: { code: 0, stdout: "task ok", stderr: "" },
		expectedStatus: "succeeded",
	},
	{
		name: "task create forces non-interactive flag when omitted",
		request: {
			action: "task",
			taskAction: "create",
			request: "Build task flow",
		},
		expectedArgs: [
			"run",
			"./packages/cli/src/index.ts",
			"task",
			"create",
			"--request",
			"Build task flow",
			"--non-interactive",
		],
		commandResult: { code: 0, stdout: "task minimal ok", stderr: "" },
		expectedStatus: "succeeded",
	},
];
